Open-reSource/openresource.dev

README.md
This PR removes the ToC from the `README.md` which can be considered useless.
Indeed, as pointed out by @hiDeoo, GitHub interface already offers a similar approach:
Since this `README.md` won't be embedded in stores contrary to `README.md`s used for libraries, it's safe to remove it to avoid to maintain it.
=> fix: remove useless ToC in `README.md`

src/pages/guide/[...slug].astro, tailwind.config.cjs
This PR adds a previous/next navigation to the chapters of the modules.
Their layout is vertical or horizontal depending on the screen size.
An xs breakpoint is added to the tailwind config to handle the layout change.
While reading the entire module, it is useful to have a navigation to the previous and next chapters.
=> feat(chapters): add previous/next buttons

.github/workflows/weekly.yaml
I did not bother creating an issue for this considering the size of the changes and the obvious impact it has, but I can if you really want to.
This pull request adds a caching mechanism of dependencies to the CI pipeline to speed up CI runs, use less compute resources and reduce the number of requests to the package manager registry.
Installing dependencies can take a long time, especially on CI and even more when using `npm`. Thanks to deterministic lockfiles, most package managers dependencies can now be cached and reused between builds, e.g. with `npm`, `yarn`, `pnpm` and even non-JS package managers like `pip`, `nugget` and `cargo`, etc.
This is the reason why [`actions/cache`](https://github.com/actions/cache) is one of the most popular actions on GitHub Actions. Unfortunately, it …
=> ci: add npm dependencies caching

src/components/ShowcaseBanner.astro, src/pages/index.astro, src/pages/showcase/index.astro
This PR adds a new `ShowcaseBanner` Astro component.
Adding projects to the showcase page can be a great value for the community. The page being "hidden" in the footer, highlighting this feature on the homepage is important. And adding this banner is also important directly on the Showcase page itself.
=> feat: add showcase banner in `/` and `/showcase`

src/components/ShowcaseBanner.astro, src/pages/index.astro
Closes #35
This PR:
* removes the 'Show projects' link in the /showcase page
* changes the wording since we now have multiple projects on the Showcase page
* modifies the alignment so that it's always horizontally centered whatever the breakpoint
=> fix(showcase): don't display 'Show projects' link

package-lock.json, package.json
Bump dependencies listed by Dependabot:
- `@astrojs/rss`: `^2.4.0` → `^2.4.1`
- `@astrojs/tailwind`: `^3.1.1` → `^3.1.2`
- `@astrojs/vercel`: `^3.2.5` → `^3.3.0`
- `astro`: `^2.4.3` → `^2.4.5`
- `daisyui`: `^2.51.5` → `^2.51.6`
- Chore (non-breaking change)
=> chore(deps): bump dependencies

src/components/ProgressScroll.astro, src/layouts/Layout.astro, src/pages/articles/[...slug].astro, src/pages/guide/[...slug].astro
This PR adds a visual progress bar on top of the website for articles and chapters to see the reading progress. It uses the percentage of the page scrolled.
Technically, my first idea is that this information is not really helpful for screen readers. But if I'm mistaken in the future based on user feedback, it can be revisited later.
Small nice indicator.
=> feat: add progress scroll to articles and chapters

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
I did not bother creating an issue for this considering the simplicity of the change.
While working on an [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) related tool and testing it against various issue forms from various repositories, I noticed that the brand name of the project is not consistent across the issue forms descriptions.
This pull request aims to fix this inconsistency by replacing the brand name with the one always used in the website, `Open {re}Source`.
This solves nothing.
- N/A
=> fix: issue form description brand name consistency

src/content/articles/can-i-take-this-issue.mdx
Add precisions regarding how to remind the fact that a repository doesn't assign issues at the end of all newly created issues. Add an Open {re}Source lab repo to support it.
See https://github.com/Open-reSource/labs-append-markdown-to-issues + https://github.com/julien-deramond/update-issue-body.
- Content (New or updated)
=> docs: update 'Can I Take This Issue?' article

src/content/articles/display-your-sponsors-in-your-github-readmes.mdx, src/pages/articles/index.astro
This PR embeds a bug fix to order the articles list by creation date. It wasn't seen before because there were only 2 articles, and they were ordered correctly by chance.
The main content of this PR is the new article named 'Display your sponsors in your GitHub READMEs'.
This new article is based on the work I wanted to do on my own personal GitHub projects. I had finally the time to find how and to put it in place. It might not be the best way of doing it, but it ends with something usable for me. So let's make it a short article for the community!
=> New article: 'Display your sponsors in your GitHub READMEs'

CONTRIBUTING.md, LICENSE, README.md, src/components/CreativeCommonMention.astro, src/pages/articles/[...slug].astro, src/pages/guide/[...slug].astro
This PR changes the license of the content of this repository from CC BY 4.0 to CC BY-NC-SA 4.0. It is still possible to change it since no content has been created or modified yet by external contributors.
It is reflected obviously in the `LICENSE` file, but also in the `README.md` file and in the `CONTRIBUTING.md` file.
This PR also displays this license in the footer of articles and guide chapters so that it is clear also for users/readers. In order to do so, a new Astro component named `CreativeCommonMention.astro` has been created.
=> feat(license): change licensing to CC BY-NC-SA 4.0 for articles and guide content

src/content/articles/display-your-sponsors-in-your-github-readmes.mdx
This PR enhances the content of the 'Display your sponsors in your GitHub READMEs' article.
In order to reduce the number of manipulations to do from the reader, https://github.com/Open-reSource/sponsorkit-starter has been created.
The article has been rewritten to make the reader start from this reusable template.
- Enhancement (non-breaking change)
=> docs(article): enhance 'Display your sponsors in your GitHub READMEs'

src/components/SkipLink.astro, src/layouts/Layout.astro
This issue closes #16.
As a heavy keyboard user, I noticed that no link to skip to the main content is present on the page. I also saw that an issue was already opened for this and as I had some time, I decided to work on it. Hope that's okay!
This PR adds a link to skip to the main content. It is hidden by default and only appears when the user focuses it.
Design-wise, it's heavily inspired by the GitHub one but feel free to change it if you want to.
It uses Tailwind [screen readers utilities](https://tailwindcss.com/docs/screen-readers#screen-reader-only-elements) to hide the link by default and show it when focused.
As stated in #16, the reasons are a obvious.
=> feat: add skip link

src/global.css
This PR closes #67.
As discussed earlier, this PR relies on DaisyUI CSS variables to use the primary color and its content variation for selections.
It should be noted that if some elements ever need different colors for their selection, a custom class could be used to override the default color, or just using a Tailwind class, e.g. `selection:bg-secondary`.
This PR aims to improve the readability of the selection colors. More context can be found in #67.
=> fix: improve selection colors readability

package-lock.json, package.json
This PR bumps `astro` dependency from `2.5.3` to `2.5.4`
Based on [astro 2.5.4](https://github.com/withastro/astro/releases/tag/astro%402.5.4), there's apparently no modification to do in this repo, nor impacts.
=> chore(deps): bump astro from 2.5.3 to 2.5.4

src/global.css, src/layouts/Layout.astro
This pull request is a follow-up of #85.
This pull request tweaks various aspects of the newly introduced search feature.
First, the search input placeholder has been updated from `"Search docs"` to `"Search Open {re}Source"`.
When the search does not return any results, the user is now presented with a message that reads `"Believe this query should return results? Let us know."` with a link to create a new issue with the title and body already pre-filled with the query. Note that it's not possible to pre-fill the OS and browser as this is [not yet supported](https://github.com/orgs/community/discussions/44983) by GitHub.
Then, the search UI has been tweaked and uses DaisyUI CSS Variables as much as possible. This gives a more personalized look to the search UI adapting to the current …
=> Search UI tweaks

src/layouts/Layout.astro
This pull request is a follow-up of https://github.com/Open-reSource/openresource.dev/pull/91.
When the search doesn't return any results, users can click on a link where "Believe this query should return results? Let us know." message is presented to them.
Originally, the link was to our bug template but needed the user to select the operating system(s) which was an extra step not useful to report search errors/enhancement.
This PR changes this link to an empty issue creation with a pre-filled title and a description, plus an "enhancement" label, and a newly created "search" label.
Example of link: https://github.com/Open-reSource/openresource.dev/issues/new?title=Search%20missing%20results%20for%20%22dfsfds%22&body=The%20search%20query%20%22dfsfds%22%20did%20not%20return%20any%20results. …
=> feat(search): change issue creation URL when search without results

package-lock.json, package.json
[astro@2.7.0](https://github.com/withastro/astro/releases/tag/astro%402.7.0):
> Remove legacy handling for MDX content collections. Ensure you are using `@astrojs/mdx` v0.18 or above:
No impact.
> `Astro.locals` is now exposed to the adapter API. Node Adapter can now pass in a `locals` object in the SSR handler middleware. 
Not used for now.
> Shipped a new SSR build configuration mode: `split`.
Created https://github.com/Open-reSource/openresource.dev/issues/127 to study it.
=> chore(deps): bump astro from 2.6.6 to 2.7.0

src/content/config.ts, src/layouts/Layout.astro, src/pages/articles/[...slug].astro
This PR adds some structured data for Open {re}Source articles based on https://developers.google.com/search/docs/appearance/structured-data/article#json-ld.
The result has been tested via https://search.google.com/test/rich-results?utm_campaign=devsite&utm_medium=jsonld&utm_source=article.
The schema is automatically filled out with the basic information from the articles' frontmatter but can be overwritten in the articles' frontmatter itself too if needed in the future.
https://main-branch-openresource-dev-git-main-jd-a-7640e3-open-resource.vercel.app/articles/github-marketplace-social-preview-for-your-github-actions contains for example:
```html
<script type="application/ld+json">{
"@context": "https://schema.org/",
"@type": "Article",
"headline": "GitHub Marketplace: Social Preview …
```
=> feat(seo): add Article structured data

src/pages/404.astro, src/util/getOpenGraphImageURL.ts
⚠️ This PR is a draft
---
404 pages generate a Content Encoding Error in the production configuration and with the main branch configuration. However, in the deployment of this branch and locally, it's working:
* 🔴 https://openresource.dev/articles/fdsfsdfsd
* 🔴 https://main-branch-openresource-dev-git-main-open-resource.vercel.app/fdsqfdsfsqd
* 🟢 https://main-branch-openresource-dev-git-main-jd-fix-404-open-resource.vercel.app/dskfdsfdfds
* 🟢 https://main-branch-openresource-dev-git-main-jd-fix-404-open-resource.vercel.app/articles/dskfdsfdfds
One solution seems to be to use `export const prerender = false` with `404.astro`. However, `npm run build` generated an error while running locally. The code using `getStaticPaths` wasn't used so is removed.
It's not possible to check whether or …
=> Fix Content Encoding Error on 404 pages

astro.config.mjs, package-lock.json, package.json, src/layouts/Layout.astro
`speedInsights` configuration was marked as deprecated in `@astrojs/vercel` version 6.1.3. Vercel has migrated features of the Speed Insights API into a framework-agnostic library with `@vercel/speed-insights`. See [Vercel Speed Insights Quickstart](https://vercel.com/docs/speed-insights/quickstart) for instructions on how to use the library instead.
This PR intends to do this migration.
=> chore(deps): add `@vercel/speed-insights`

src/content/config.ts, src/content/modules/creating-your-own-open-source-project/developing-your-project.mdx, src/content/modules/creating-your-own-open-source-project/legal-considerations.mdx, src/content/modules/maintaining-open-source-projects/fostering-a-strong-and-inclusive-community.mdx, src/pages/guide/[...slug].astro
At the time of writing this PR, most of the modules, and their chapters, are not entirely written or structured with a final version in mind. An information needs to be displayed at the end of these chapters to inform the reader that this chapter is not considered as "finished" (even if they will never be finished, they could contain at least the topics I'd like to tackle in the first place).
This PR adds a "finished" optional frontmatter option.
When there's a `finished: false` in the frontmatter, there's a warning banner displayed at the end of the chapter.
This PR also flags some chapters as "not finished" that weren't flagged like this before.
=> feat: add `finished: false` frontmatter option for chapters

package-lock.json, package.json, src/components/Head.astro, src/components/Header.astro, src/components/PageTitleThenReadingTime.astro
This PR bumps starlight-blog from 0.12.0 to 0.13.0. [This new release](https://github.com/HiDeoo/starlight-blog/releases/tag/v0.13.0) embeds a new feature that mainly does not have any impacts on the rendering as there's only one author for the articles.
However, when running `npm run build`, we can see that a new page is generated: [/articles/authors/julien-déramond](https://main-branch-openresource-dev-git-main-jd-b-9868b2-open-resource.vercel.app/articles/authors/julien-d%C3%A9ramond)
This page is not an issue, but we want to remove the reading time, and maybe check at other places in the code if we need to do some other modifications. For instance, with the OG images.
=> chore(deps-dev): bump starlight-blog from 0.12.0 to 0.13.0

src/components/Head.astro
This PR fixes the warning observed when running `npm run build`:
```fish
src/components/Head.astro:83:27 - warning astro(4000): This script will be treated as if it has the `is:inline` directive because it contains an attribute. Therefore, features that require processing (e.g. using TypeScript or npm packages in the script) are unavailable.
See docs for more details: https://docs.astro.build/en/guides/client-side-scripts/#script-processing.
Add the `is:inline` directive explicitly to silence this hint.
83 {articleSchema && <script type="application/ld+json" set:html={articleSchema} />}
```                             ~~~~
=> fix(build): use `is:inline` to script embedded in `Head.astro`

src/components/GuideReadingTime.astro, src/content/docs/guide/contributing-to-open-source-projects/index.mdx, src/content/docs/guide/creating-your-own-open-source-project/index.mdx, src/content/docs/guide/financing-open-source-projects/index.mdx, src/content/docs/guide/getting-started-with-open-source/index.mdx, src/content/docs/guide/index.mdx, src/content/docs/guide/maintaining-open-source-projects/index.mdx, src/content/docs/guide/promoting-open-source-projects/index.mdx, src/content/docs/guide/what-is-open-source/index.mdx
Closes #887
This PR improves the interface provided by `<GuideReadingTime>` component, which is now able to understand its current context/slug.
=> feat(components): improve `GuideReadingTime` interface by removing properties

tests/showcase.test.ts
for 'should delete the existing showcase content collection before saving showcases to handle deleted comments' test
The test suite worked locally but not anymore in GitHub integration testing context (without any changes).
=> fix(tests): `AssertionError: expected false to be true // Object.is equality`
